### PR TITLE
Make it possible to compile using a Docker image

### PR DESCRIPTION
**Pull request by trivoallan**

### CODE REVIEW

**Comment by badgeek** [comment]
@trivoallan  thanks, are you actively using this?

**Comment by trivoallan** [comment]
@badgeek No, i built it for a friend who add trouble compiling the extension on his computer. But he will be using it actively i guess.

**Comment by badgeek** [comment]
@trivoallan okay thanks for the PR, happy to see this still useful. :)

**Comment by trivoallan** [comment]
@badgeek Great :) Are you interested into having admin access to the Docker Hub repository ?

**Comment by badgeek** [comment]
@trivoallan i guess i dont have time to maintain this anymore, but will let u know if i need that access, thanks!

**Pull request merged**
